# Yarn configuration for MirrorStack Wallet
# This file configures yarn behavior for the project

# Enable PnP (Plug'n'Play) for better performance
nodeLinker: node-modules

# Enable zero-installs for faster builds
enableGlobalCache: true

# Configure network settings
httpTimeout: 60000
networkTimeout: 60000

# Enable strict SSL
enableStrictSsl: true

# Configure registry
npmRegistryServer: 'https://registry.npmjs.org'

# Enable audit for security
enableAudit: true

# Configure workspaces (if needed in future)
workspaces:
  - 'src/**'

# Enable immutable installs
enableImmutableInstalls: true

# Configure log level
logFilters:
  - code: YN0013
    level: discard
